---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for budget-tracker-api

Globals:
  Function:
    Timeout: 3

Resources:
  GetCategoryTotalsProd:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - arn:aws:iam::621544995223:policy/ECR-read
      AutoPublishAlias: live
      DeploymentPreference:
        Type: LambdaCanary10Percent5Minutes
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1

Outputs:
  GetCategoryTotalsApiProd:
    Description: "API Gateway endpoint URL for Prod stage for the GetCategoryTotalsProd function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetCategoryTotalsProd:
    Description: "GetCategoryTotalsProd Lambda Function ARN"
    Value: "GetCategoryTotalsProd.Arn"
  GetCategoryTotalsIamRoleProd:
    Description: "Implicit IAM Role created for GetCategoryTotalsProd function"
    Value: !GetAtt GetCategoryTotalsProdRole.Arn
