---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for budget-tracker-api

Globals:
  Function:
    Timeout: 3

Resources:
  GetCategoryTotals-prod:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - arn:aws:iam::621544995223:policy/ECR-read
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1

Outputs:
  GetCategoryTotalsApi-prod:
    Description: "API Gateway endpoint URL for Prod stage for the GetCategoryTotals-prod function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetCategoryTotals-prod:
    Description: "GetCategoryTotals-prod Lambda Function ARN"
    Value: "GetCategoryTotals-prod.Arn"
  GetCategoryTotalsIamRole-prod:
    Description: "Implicit IAM Role created for GetCategoryTotals-prod function"
    Value: !GetAtt GetCategoryTotalsRole.Arn
