---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for budget-tracker-api

Globals:
  Function:
    Timeout: 10

Resources:
  GetCategoryTotals:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - arn:aws:iam::621544995223:policy/ECR-read
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForCloudFormation
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      AutoPublishAlias: live
      DeploymentPreference:
        Type: LambdaCanary10Percent1Minute
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./

Outputs:
  GetCategoryTotalsApi:
    Description: "API Gateway endpoint URL for the GetCategoryTotals function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  GetCategoryTotals:
    Description: "GetCategoryTotals Lambda Function ARN"
    Value: "GetCategoryTotals.Arn"
  GetCategoryTotalsIamRole:
    Description: "Implicit IAM Role created for GetCategoryTotals function"
    Value: !GetAtt GetCategoryTotalsRole.Arn
