AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for budget-tracker-api

Parameters:
  env:
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  !Sub "GetCategoryTotals-${env}":
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Policies:
        - arn:aws:iam::621544995223:policy/ECR-read
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1

Outputs:
  GetCategoryTotalsApi:
    Description: !Sub "API Gateway endpoint URL for Prod stage for the GetCategoryTotals-${env} function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  !Sub "GetCategoryTotals-${env}":
    Description: !Sub "GetCategoryTotals-${env} Lambda Function ARN"
    Value: !Sub "GetCategoryTotals-${env}.Arn"
  GetCategoryTotalsIamRole:
    Description: !Sub "Implicit IAM Role created for GetCategoryTotals-${env} function"
    Value: !GetAtt GetCategoryTotalsRole.Arn
